parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geography:  CrEOF\Spatial\DBAL\Types\GeographyType
            polygon:    CrEOF\Spatial\DBAL\Types\Geography\PolygonType
            point:      CrEOF\Spatial\DBAL\Types\Geography\PointType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Main:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/AppMain/Entity'
                prefix: 'App\AppMain\Entity'
                alias: App
            Admin:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/AppManage/Entity'
                prefix: 'App\AppManage\Entity'
                alias: App
