framework:
    secret: '%env(APP_SECRET)%'
    default_locale: bg
    csrf_protection: true
    #http_method_override: true

    session:
      handler_id: ~
      cookie_secure: auto
      cookie_samesite: lax

    assets:
        packages:
            manage:
                base_path: 'assets/core-ui'
            front:
                base_path: 'assets/front'

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        prefix_seed: vs/gsr

        #default_redis_provider: redis://localhost

