# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: bg
    csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    assets:
        packages:
            manage:
                base_path: 'assets/core-ui'
            front:
                base_path: 'assets/front'

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        prefix_seed: vs/gsr

        #default_redis_provider: redis://localhost

