framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            App\Message\RebuildStyleByAnswer:  async
            App\Message\RebuildStyleByQuestion:  async
