security:
    encoders:
        App\AppMain\Entity\User\User:
            algorithm: argon2i
            memory_cost: 2048
            time_cost: 2
            threads: 2

    providers:
        db_provider:
            entity:
                class: App\AppMain\Entity\User\User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_MANAGE
        ROLE_MANAGE: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            remember_me:
                secret: '%kernel.secret%'
                name: REM
                lifetime: 31536000
                path: /
                #domain:
                #secure: auto
                #httponly:
                #samesite:
                #remember_me_parameter:
                #always_remember_me:
                #token_provider:
            logout:
                path:   logout
                target: /
            guard:
                provider: db_provider
                entry_point: App\Security\LoginFormAuthenticator
                authenticators:
                    - App\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/manage, roles: ROLE_MANAGE }