<?php

namespace App\AppMain\Entity\Survey\Question;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
}
