<?php


namespace App\Services;


class Constant
{
    public const GEOMETRY_TYPE_POINT = 'POINT';
    public const GEOMETRY_TYPE_LINESTRING = 'LINESTRING';
    public const GEOMETRY_TYPE_POLYGON = 'POLYGON';
    public const GEOMETRY_TYPE_MULTIPOINT = 'MULTIPOINT';
    public const GEOMETRY_TYPE_MULTILINESTRING = 'MULTILINESTRING';
    public const GEOMETRY_TYPE_MULTIPOLYGON = 'MULTIPOLYGON';
    public const GEOMETRY_TYPE_GEOMETRYCOLLECTION = 'GEOMETRYCOLLECTION';
}