openapi: 3.0.0
info:
  version: "1.0.0"
  title: Front-end API
tags:
- name: "survey"
  description: "Geo-object survey interaction"

paths:
  /front-end/geo-object/{id}/survey:
    get:
      tags:
      - "survey"
      summary: ""
      operationId: ""
      description: ""
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: geo-object id
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'

        '400':
          description: ""
    post:
      tags:
      - "survey"
      summary: ""
      operationId: ""
      description: ""
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: geo-object id
      requestBody:
        description: Array of answer id's
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SurveySubmitRequest'



      responses:
        '200':
          description: ""

        '400':
          description: ""

components:
  schemas:
    SurveySubmitRequest:
      type: "object"
      required:
        - "answers"
      properties:
        answers:
          type: "array"
          items:
            type: "string"
            format: uuid
          example:
            - "edefef32-e8b4-4ca7-8c3b-9d6e225f6111"
            - "2a4bfc26-cccc-4bee-962d-666469025573"

    Question:
      type: object
      required:
        - question
        - has_multiple_answers
        - answers
      properties:
        question:
          type: string
          format: uuid
          example: Какъв е автомобилният трафик в момента?
        has_multiple_answers:
          type: boolean
          example: false
        answers:
          type: "array"
          items:
            $ref: '#/components/schemas/Answer'

    Answer:
      required:
        - id
        - title
        - is_free_answer
        - parent
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          format: text
        is_free_answer:
          type: boolean
          example: false
        parent:
          type: string
          nullable: true
          format: uuid
      type: object