public:
  resource: '../src/AppManage/Controller/'
  type:     annotation
  prefix: /manage

api-front-end:
  resource: '../src/AppMain/Controller/APIFrontEnd'
  type:     annotation
  prefix: /front-end

logout:
  path: /logout