manage:
  resource: '../src/AppManage/Controller/'
  type:     annotation
  prefix: /manage

api-front-end:
  resource: '../src/AppAPIFrontend/Controller'
  type:     annotation
  prefix: /front-end

logout:
  path: /logout